### ISSUE TITLE
Setup initial project environment

### ISSUE THREAD

**Issue by Kijung-Luke-Kim** [Kijung-Luke-Kim/community-api#1]
## TODO
- [ ] segregate development/staging/production environment and settings
- [ ] create simple api for posts and comments
- [ ] set and document links and rules for this project
